version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: sequencesender_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - "${POSTGRES_VOLUME_PATH}:/var/lib/postgresql/data"

volumes:
  postgres_data: 